### ISSUE TITLE
For real industrial application, what strategy to locate the exact table?

### ISSUE THREAD

**Issue by guotong1988** [beader/tianchi_nl2sql#14]
The datasets is that the table corresponding to question is given.

But in real industrial application, we have 100+ tables for 1 new question.

Thank you!

真正落地的时候，给一个问题，会有100多张表候选，要先定位到表，才能生成SQL，这个有什么方法定位到表？

**Comment by beader** [comment]
I think linking questions and tables is another topic. Maybe extra models can be used to solve the problem. I have no experience on this topic. Thanks!
