### ISSUE TITLE
关于model1里面pred_sqls的问题

### ISSUE THREAD

**Issue by yuanhuang0809** [beader/tianchi_nl2sql#15]
您好，看到您的代码有完整的解释和代码，想学习一下，有一个疑问，请问为什么在model1中预测sql，用的是验证集序列decode呢？
`    sqls = outputs_to_sqls(preds_cond_conn_op, preds_sel_agg, preds_cond_op, 
                           header_lens, val_dataseq.label_encoder)`

期待您的答复，谢谢~

**Comment by beader** [comment]
其实这里的 `val_dataseq.label_encoder` 就是全局变量 `label_encoder `。所以这里不需要特别去使用`val_dataseq.` 作为前缀。感谢你的细心。

**Comment by FileNotFound-404** [comment]
好的，谢谢您的回复
