### ISSUE TITLE
这个地方有些不理解

### ISSUE THREAD

**Issue by LuGuangWang** [beader/tianchi_nl2sql#16]
# predict cond_conn_op
x_for_cond_conn_op = Lambda(lambda x: x[:, 0])(x) # (None, 768)

这块代码的意思是？
只用句子的第一个词的语义向量进行cond_conn_op预测？

**Comment by beader** [comment]
是的，每个句子第一个词是 `[CLS]`， `[CLS]` 一定程度反应了句子的全局信息。
