### ISSUE TITLE
task1关于DataSequence随机输出的问题

### ISSUE THREAD

**Issue by xudongMk** [beader/tianchi_nl2sql#21]
train_seq = DataSequence(train_data, query_tokenizer, label_encoder, shuffle=False, max_len=160, batch_size=2)
sample_batch_inputs, sample_batch_outputs = train_seq[0]
这个里面取索引为0的数据
for name, data in sample_batch_outputs.items():
    print('{} : shape{}'.format(name, data.shape))
    print(data)
打印sample_batch_outputs这个data，发现每次运行都是不一样的。请问是为何？

**Comment by beader** [comment]
为了让样本更丰富，增加了 `shuffle_header` 的功能，意思是每次拿样本的时候，会随机打乱表头的顺序。可以通过设置 `shuffle_header=False` 来关闭这个功能。

**Comment by xudongMk** [comment]
刚

> 为了让样本更丰富，增加了 `shuffle_header` 的功能，意思是每次拿样本的时候，会随机打乱表头的顺序。可以通过设置 `shuffle_header=False` 来关闭这个功能。

刚看到，谢谢回复。
