### ISSUE TITLE
关于先训练后加载模型预测ValueError

### ISSUE THREAD

**Issue by xudongMk** [beader/tianchi_nl2sql#22]
博主您好，当前训练完成后，后续通过其他脚本重新加载model的时候，出现了报错：
ValueError: You are trying to load a weight file containing 1 layers into a model with 4 layers.
用的是save_weights 和 load_weights~~~
请问有没有遇到过~~~

**Comment by beader** [comment]
估计你是用了多个GPU做训练，用单个GPU来load模型。多个GPU的模型，你summary出来看看，提取有用的那几层出来 save

**Comment by xudongMk** [comment]
> 估计你是用了多个GPU做训练，用单个GPU来load模型。多个GPU的模型，你summary出来看看，提取有用的那几层出来 save
是的，刚也发现了这个问题。我是用gpu训练的然后用cpu去加载的~~~~

**Comment by xudongMk** [comment]
多谢~~~
