### ISSUE TITLE
model1中outputs_to_sqls函数里对cond_op和sel_agg的处理为何不同？

### ISSUE THREAD

**Issue by Vincentyua** [beader/tianchi_nl2sql#23]
您好，我比较疑惑，在outputs_to_sqls函数中为何sel_agg要强制给column选一个agg，这里理解cond_op与sel_op的情况是类似的，都是column在分布上的概率，感觉sel_agg和cond_op一样直接做argmax就可以得到预测的label，不明白为啥还要再单独处理一下，希望得到您的解答

**Comment by beader** [comment]
注意到，sel_agg 最开始是一个2维度数组

**Comment by beader** [comment]
为了更好到说明问题，这里假设有 3 个 columns，有 `''`, `AVG`, `NO_OP` 这 3 种 agg。
模型预测出来的 sel_agg 可能是如下的样子:

```
[
 [ 0.10, 0.40, 0.50 ],
 [ 0.14, 0.26, 0.60 ],
 [ 0.15, 0.30, 0.55 ]
]
```

此时对 sel_agg 做 `argmax(axis=-1)` 操作，将得到:

```
[
 2,
 2,
 2
]
```

这意味着，所有的 column 将全部不被选中 (即 `NO_OP`)。对于竞赛而言，这不是一条有效的 SQL，因为这条 SQL 并未选择任何的 column。退而求其次的一种做法是，选取剩下”最有可能被选中的那个column"，我这里具体做法是，忽略每个 column 对于 `NO_OP` 的概率预测，在剩下的概率中，拿到概率最大的那个值，(上例中为 `sel_agg[0][1]` )，将它设置为 1

```
[
 [ 0.10, 1.00, 0.50 ],
 [ 0.14, 0.26, 0.60 ],
 [ 0.15, 0.30, 0.55 ]
]
```

此时再去做 `argmax(axis=-1)` 操作，将得到:

```
[
 1,
 2,
 2
]
```
这种做法，保证了，至少有一列会被选中，同时，不会改变其他列的预测结果。

**Comment by Vincentyua** [comment]
666，这个做法很巧妙，很nice。感谢及时回答

**Comment by Vincentyua** [comment]
不过，这样的做法可能会误伤一部分，比如sel_agg如下：

> `[
> [ 0.15,  0.42, 0.43]
> [ 0.40, 0.30, 0.30]
> ]`

这样的话，原本预测的结果应该是

> `[
> [2]
> [1]
> ]`

但是强制选择一个后，就会变为

> `[
> [1]
> [1]
> ]`
>

**Comment by beader** [comment]
您上面的例子中:

> `[
> [ 0.15,  0.42, 0.43]
> [ 0.40, 0.30, 0.30]
> ]`

取 argmax(axis=-1) 的结果应该是:

> `[ [2], [0] ]`

做了前处理之后，最终的结果会变成

> `[ [1] [0] ]`

确实会导致“误伤”。一种可能的补救方法是，先确定是否一个列都未选中，如果是，才做这种前处理，否则不做。

**Comment by Vincentyua** [comment]
对的对的，我手误了，不过还是很nice的处理，这都是小事了，前面判断一下也很简单
