### ISSUE TITLE
Model2的pattern 模板问题

### ISSUE THREAD

**Issue by Brian1203** [beader/tianchi_nl2sql#29]
Model2的pattern 模板中，不考虑 “不等于“ 的情况 。请问是有意为之嘛？

**Comment by beader** [comment]
因为竞赛的数据中，几乎没有这个情况，所以直接拿掉了。数据分布的原因，真实场景需要考虑。

**Comment by vcbeaut** [comment]
> Model2的pattern 模板中，不考虑 “不等于“ 的情况 。请问是有意为之嘛？

您好，官方现在下载不了数据集，您可以提供发我一份吗？万分感谢。2191265529@qq.com

**Comment by vcbeaut** [comment]
> 因为竞赛的数据中，几乎没有这个情况，所以直接拿掉了。数据分布的原因，真实场景需要考虑。

您好，官方现在下载不了数据集，您可以提供发我一份吗？万分感谢。2191265529@qq.com
