### ISSUE TITLE
关于数据集的请求

### ISSUE THREAD

**Issue by Slivery455** [beader/tianchi_nl2sql#37]
大佬您好，如果可以的话，能给我发一下数据集的规格吗，数据我可以自己造，但是没有格式真的无从下手，谢谢！

**Comment by Slivery455** [comment]
我又来了=w=请问这个“sel"的标号是0开始还是1开始？看示例”世茂茂悦府“对应的是”1“，但是下面的"header"不论是第一还是第二字段都不像能对上的样子？

**Comment by beader** [comment]
> 大佬您好，如果可以的话，能给我发一下数据集的规格吗，数据我可以自己造，但是没有格式真的无从下手，谢谢！

https://github.com/ZhuiyiTechnology/TableQA
