### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by qqxze** [beader/tianchi_nl2sql#8]
您好，看了您的分享，深受鼓舞，请问您能提供一些数据以供学习嘛，谢谢啦

**Comment by beader** [comment]
主办方最近会开源数据集，可以关注一下

**Comment by qqxze** [comment]
好的 是在天池上公开嘛？




------------------ 原始邮件 ------------------
发件人: "beader"<notifications@github.com>;
发送时间: 2019年10月23日(星期三) 下午2:47
收件人: "beader/tianchi_nl2sql"<tianchi_nl2sql@noreply.github.com>;
抄送: "朱琪超"<839983653@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [beader/tianchi_nl2sql] 数据集 (#8)




主办方最近会开源数据集，可以关注一下

**Comment by beader** [comment]
可以关注一下追一的公众号，估计开源的时候会宣布

**Comment by qqxze** [comment]
好嘞，谢谢啦



---原始邮件---
发件人: "beader"<notifications@github.com&gt;
发送时间: 2019年10月23日(星期三) 下午5:45
收件人: "beader/tianchi_nl2sql"<tianchi_nl2sql@noreply.github.com&gt;;
抄送: "zhuzhu"<839983653@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [beader/tianchi_nl2sql] 数据集 (#8)



可以关注一下追一的公众号，估计开源的时候会宣布

**Comment by hydercps** [comment]
您好，请问您看过排在WikiSQL 第一的X-SQL那篇文章吗？它的代码公开了吗？
非常感谢！

**Comment by beader** [comment]
@hydercps 没看过

**Comment by ZizhenWang** [comment]
@qqxze 请问你拿到数据了么？

**Comment by qqxze** [comment]
没有呐 我现在已经不做这方面研究 就没有继续跟进 数据的情况了&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月2日(星期天) 下午2:22
收件人:&nbsp;"beader/tianchi_nl2sql"<tianchi_nl2sql@noreply.github.com&gt;;
抄送:&nbsp;"朱琪超"<839983653@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [beader/tianchi_nl2sql] 数据集 (#8)




@qqxze 请问你拿到数据了么？

**Comment by superccy** [comment]
您好，请问您有数据集吗，错过了比赛，想自己先研究一下，麻烦还能共享下数据吗？非常非常感谢！如果可以麻烦请发到邮箱643958081@qq.com。已经star,希望麻烦您给发一份数据

**Comment by vcbeaut** [comment]
> 您好，请问您有数据集吗，错过了比赛，想自己先研究一下，麻烦还能共享下数据吗？非常非常感谢！如果可以麻烦请发到邮箱[643958081@qq.com](mailto:643958081@qq.com)。已经star,希望麻烦您给发一份数据

您好，官方现在下载不了数据集，您可以提供发我一份吗？万分感谢。2191265529@qq.com

**Comment by myboyliu** [comment]
您好，官方现在下载不了数据集，您可以提供发我一份吗？万分感谢。271584740@qq.com

**Comment by LeiyanGithub** [comment]
您好，官方现在下载不了数据集，您可以提供发我一份吗？万分感谢。2649429221@qq.com

**Comment by qqxze** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到，谢谢哦。

**Comment by szj2ys** [comment]
您好，官方现在下载不了数据集，您可以提供发我一份吗？万分感谢。15574364821@163.com

**Comment by qqxze** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到，谢谢哦。

**Comment by shuoshuo0** [comment]
您好 是否可以提供一份数据集给我？万分感谢。z15531294696@163.com

**Comment by qqxze** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到，谢谢哦。

**Comment by qihuagaosh** [comment]
您好 是否可以提供一份数据集给我？万分感谢。gaoqihua@futuredatech.com

**Comment by qqxze** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到，谢谢哦。

**Comment by ZXtreme** [comment]
您好 是否可以提供一份数据集给我？万分感谢。zxtreme@qq.com

**Comment by qqxze** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到，谢谢哦。

**Comment by Impressedecho** [comment]
您好，官方现在下载不了数据集，您可以提供发我一份吗？万分感谢。760989105@qq.com

**Comment by qqxze** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到，谢谢哦。

**Comment by chenrui2200** [comment]
好，官方现在下载不了数据集，您可以提供发我一份吗？万分感谢。 370299412@qq.com

**Comment by qqxze** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到，谢谢哦。

**Comment by hjing100** [comment]
您好，现在官网下载不了数据集，可以发我一份吗，万分感谢。2287929669@qq.com

**Comment by qqxze** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到，谢谢哦。

**Comment by brainsboom** [comment]
> 这是来自QQ邮箱的自动回复邮件。   您好，邮件已收到，谢谢哦。

请问还有数据集吗

**Comment by qqxze** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到，谢谢哦。

**Comment by beader** [comment]
> > 这是来自QQ邮箱的自动回复邮件。   您好，邮件已收到，谢谢哦。
> 
> 请问还有数据集吗

@brainsboom  https://github.com/ZhuiyiTechnology/TableQA

**Comment by beader** [comment]
数据集已经在 https://github.com/ZhuiyiTechnology/TableQA 公布
