### ISSUE TITLE
model2 保存  load的时候有错误

### ISSUE THREAD

**Issue by luv4me** [beader/tianchi_nl2sql#9]
model.save('model2.h5')
model = load_model('model2.h5') 
我是用这个方法保存的  读取时候报错 ValueError: Unknown layer: TokenEmbedding 然后我没找到自定义的TokenEmbedding  我想问下这个应该怎么把它加载到load_model里面

**Comment by beader** [comment]
建议你尝试一下用 save_weights 和 load_weights 来加载模型
